name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install
        run: npm i

      - name: Lint
        run: npm run lint

  test-unit:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Set node
        uses: actions/setup-node@v3
        width:
          node-version: 16.x

      - name: Install
        run: npm i

      - name: Test
        run: npm run test:ci

      - name: Report Coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v1

  test-ui:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Set node
        uses: actions/setup-node@v3
        width:
          node-version: 16.x

      - name: Install
        run: npm i

      - name: Test
        run: npm run test:ui
